from datetime import datetime
import os

def Save_Exception(exception: Exception):
    datetime.now()